name: info_bot
description: A Flutter app UI for InfoBot chat as per design.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png
    - assets/user.png
    - assets/bot.png